apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflare-tunnel
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: cloudflare-tunnel-credentials
  data:
    - secretKey: api-token
      remoteRef:
        key: CLOUDFLARE_API_TOKEN
    - secretKey: cloudflare-account-id
      remoteRef:
        key: CLOUDFLARE_ACCOUNT_ID
    - secretKey: cloudflare-tunnel-name
      remoteRef:
        key: CLOUDFLARE_TUNNEL_NAME
